CREATE TYPE "SessionType" AS ENUM ('OLYMPIC_LIFTING', 'WOD');
ALTER TABLE "Session" ADD COLUMN "type" "SessionType" NOT NULL DEFAULT 'OLYMPIC_LIFTING', ADD COLUMN "workout" TEXT, ADD COLUMN "results" TEXT;
